### ISSUE TITLE
[Meta] Todo

### ISSUE THREAD

**Issue by adhusson** [adhusson/solcco#3]
- [ ] Change line-comment style to sticker-like
- [ ] Change light pruple to very light orange/yellow (warm), more paper-like
- [ ] Add dark mode
- [ ] Restyle left column (same font as main text), slightly darker background than main
- [ ] When code is contracted, greyout unrelated comment blocks to mark lack of matching with facing code
